### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by creeperplayer20** [Muqsit/Wilderness#11]
● Add custom cooldown before teleportation (You'll be teleported in X sec)
● If player moves teleportation will be cancelled (Please don't move when teleporting!)
● Cooldown before another command execution (Please wait X sec before using /wild again!)
● Custom aliases ('/rtp', '/rt', ...)
● World blacklist

**Comment by Muqsit** [comment]
> ● Add custom cooldown before teleportation (You'll be teleported in X sec)
> ● If player moves teleportation will be cancelled (Please don't move when teleporting!)

I feel like custom cooldown is a whole another feature and should be provided by a dedicated plugin so other plugins like this one can integrate it.


> ● Custom aliases ('/rtp', '/rt', ...)

For custom aliases, you can edit `pocketmine.yml` and specify aliases for `wilderness` command
```yaml
aliases:
  rtp: wilderness
  rt: wilderness
```


> ● World blacklist

World blacklist does exist, see `plugin_data/Wilderness/behaviours/wilderness-default.yml`
```yaml
# Configure which worlds /wilderness should (or should not) work in
worlds:
  # The type of the list. Available types:
  #   blacklist: All worlds listed in "list" are forbidden
  #   whitelist: Only the worlds listed in "list" are permitted
  type: blacklist
  list:
    - "nether" # highest block in the nether is always at y=128, so this plugin won't work properly in the nether
```
